version: "3.9"
services:
  lume:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: lume
    environment:
      - TZ=Europe/Belgrade
      - SECRET_KEY=${SECRET_KEY:?set_SECRET_KEY_in_environment}
      - DEFAULT_LANGUAGE=ru
      - DB_PATH=/app/data/lume.db
      - COOKIE_SECURE=${COOKIE_SECURE:-false}
    volumes:
      - ../data:/app/data
    ports:
      - "8080:8080"
    restart: unless-stopped
